### ISSUE TITLE
Fulcrum PyBackup module

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/pyfulcrum#2]
Fulcrum Webhooks enable receiving notifications every time an action is performed on forms and records. When a form or a record is created / updated / deleted Fulcrum calls a registered URL, sending a payload containing all the relevant informations about the event and the content being edited.

This is the core standalone Python module that implements:

- **the webhook logic**
- **data processing**
- **backup functionalities**

The main tasks for this are the following:

- [x] The python module will receive the Fulcrum's payload through his own APIs. Incoming requests will be queued to be processed asynchronously (requires #3).

- [x] The first available request payload (the Fulcrum Record) will be extracted from the queue and then it will be filtered and validated according to a set of predefined rules (requires #4).

- [x] The Record will be properly parsed to fetch (using the Fulcrum APIs) the connected informations and meta informations (requires #5).

- [x] The collected information will be properly stored according to the PyFulcrum DB schema (requires #6)

- [x] The PyBackup module will expose also specific APIs to gain access and export the contents stored in the PostgreSQL database (requires #7)
